### ISSUE TITLE
[BUG] Current folder with spaces does not watch

### ISSUE THREAD

**Issue by asinino** [nx-dotnet/nx-dotnet#308]
**Describe the bug**
On my local computer, the project I'm working on includes spaces on the folder, trying to run 'nx serve api' bugs out with the message: 
>  watch : The project file 'C:\Users\user\Documents\Projects\Team Workload\apps\api\C:\Users\user\Documents\Projects\Team' does not exist..

I tried to solve the problem locally and the solution is easy, on DotNetClient.run just convert the cmd variable to an array of parameters:
```javascript
let cmd = watch ? [`watch`, `--project`, project, `run`] : [`run`, `--project`, project];
```

Do the proper changes to accumulate the function parameter 'parameters'. And to print the message on the console just do a `.join(' ')`

**To Reproduce**

1. run 'nx serve api'

**Expected behavior**
The project API should be served as described in the documentation.

**Environment:**

- OS: used Windows but probably any OS
- Version: 1.8.0
- DotnetClient

**Comment by asinino** [comment]
How can I push the fix to the repository?

**Comment by AgentEnder** [comment]
Hey @asinino, sorry I've been away for paternity leave at work, and trying to stay away to spend time with family. If you have WSL setup on windows, I can verify the repo works well under it. Further tooling changes would have to wait for me to be back, unless you feel like working on those and then I can review them.

**Comment by asinino** [comment]
Hello
Took some time to have spare time to do this.

I added a PR that encloses the project path + name with double quotes (present ao all commands referencing a project).
I did not add a test for this situation, a name with spaces and or a parent folder name with spaces, is the test a requirement? If needed how can I develop this solution?

**Comment by AgentEnder** [comment]
The test would be nice, but this is fine as-is IMHO. The `dotnet` package itself is pretty light on tests, if one were to be added I'd recommend just adding an e2e test in the core-e2e project since there are not currently e2e tests set up for the `dotnet` project.

Eventually, we should probably set up e2e for it, shouldn't be hard but isn't currently done.

**Comment by AgentEnder** [comment]
Hmmmm, that doesn't seem like something that should have been changed by your previous PR. We've always passed fully resolved paths to the dotnet commands, and the updates you added shouldn't have changed anything with that. Let me look into it real quick.

**Comment by asinino** [comment]
Ok, I'll convert the cmd into an array of arguments, it should fix the issue.

I'm having some trouble testing it offline, how can I run it locally? I changed the way Verdaccio is called and now it's correctly initialized. But the command to publish-local is falling (I'll open a new issue for this and try to properly supply a fix).

I don't control everything on my current machine and the environment does not allow me to have WSL :/

**Comment by asinino** [comment]
Also, change this ticket back to open because the currently applied fix is breaking the package.

**Comment by ntziolis** [comment]
Running into the same issue:
- Installed this lib via `npm install --save-dev @nx-dotnet/core`
- Created a new web api project via nx console
- Executed serve for project via nx console (command used is `npx nx serve my-project-name`

Output
```
Executing Command: dotnet watch --project "/home/username/code/reponame/apps/my-project-name/My.Project.Name.csproj" run --configuration Debug 
watch : The project file '/home/username/code/reponame/apps/my-project-name/"/home/username/code/reponame/apps/my-project-name/My.Project.Name.csproj"' does not exist.
```

When executing the command listed above in bash directly the web api starts up right away no issues, for refrence this is the command that works:
```
dotnet watch --project "/home/username/code/reponame/apps/my-project-name/My.Project.Name.csproj" run --configuration Debug 
```

Given that the issue is path based this seems rather central and I would guess that right now running dotnet apps via the serve command is broken in general in the latest version.

Any timeline on a fix?

**Comment by AgentEnder** [comment]
CC @asinino I pushed some updates to your branch and went ahead and merged it. Going to cut a release soon to fix since its pretty urgent bug. Everything looks fine testing locally, and E2E passed.

**Comment by ntziolis** [comment]
I can confirm this fixed the bug for us. Hella quick turnaround guys, keep it up !!!

**Comment by asinino** [comment]
I couldn't test it locally, it always failed, with my version of dotnet-format it still fails because the parameter "--check" does not exist.

Still, I pushed a fix to execute return the buffer from stdout. Can you see the change? Do I need another pull request?

**Comment by AgentEnder** [comment]
@asinino Open a new issue for the `dotnet-format` bug, I verified it worked with dotnet 5.0.203 and 6.0.200 locally.
